### ISSUE TITLE
M2E Error

### ISSUE THREAD

**Issue by nin3tin** [drdaxxy/SimpleROHook#2]
SRH works fine if m2e is disabled but my RO crashes when m2e is enabled. Can you please help me fix this problem?

[_simplerohook.log](https://github.com/drdaxxy/SimpleROHook/files/1737884/_simplerohook.log)

Im playing in a private server http://shadowro-online.xyz/

OS is win10 1709

Hoping you can help me, thank you.

**Comment by nin3tin** [comment]
Sometimes it works but mostly it Crashes my RO
When it works it looks like this an incomplete LandPro

https://i.imgur.com/ClerCrB.png

**Comment by drdaxxy** [comment]
Sorry, I only make an effort to support the latest iRO client version. For other clients you'd have to ask other devs.
